# Generated by Django 3.1.1 on 2020-10-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default=None, max_length=4096),
        ),
    ]
